apiVersion: v1
kind: Pod
metadata:
  name: sa-token-test
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox:1.28
    name: container-test
    volumeMounts:
    - mountPath: /service-account
      name: token-vol
      readOnly: true
  serviceAccountName: default
  volumes:
  - name: token-vol
    projected:
      sources:
      - serviceAccountToken:
          audience: api
          expirationSeconds: 3600
          path: token
