apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox:1.28
    name: container-test
    volumeMounts:
    - mountPath: /projected-volume
      name: all-in-one
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          items:
          - key: username
            path: my-group/my-username
          name: mysecret
      - secret:
          items:
          - key: password
            mode: 511
            path: my-group/my-password
          name: mysecret2
