apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
spec:
  containers:
  - args:
    - sleep
    - "86400"
    image: busybox:1.28
    name: test-projected-volume
    volumeMounts:
    - mountPath: /projected-volume
      name: all-in-one
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass
