apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: nginx
    name: test
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: config
      subPath: html
    - mountPath: /etc/nginx/nginx.conf
      name: config
      subPath: nginx.conf
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: test-nfs-claim
